[package]
name = "holyrig"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
configparser = "3.1.0"
eframe = "0.31.1"
egui = "0.31.1"
egui_dock = "0.16.0"
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
toml = "0.8.20"
xdg = "2.5.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
