[package]
name = "holyrig"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_dock = "0.16.0"
tokio = { version = "1.44.1", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
